version: '2.1'
services:
  app:
    build: .
    volumes:
      - .:/app
      - home:/home/
      - node_modules:/app/node_modules/
    working_dir: /app
    entrypoint: node /app/lib/docker/entrypoint.js
    links:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - SELENIUM_BROWSER=chrome
      - HOST_USER=a11y_user
      - USER_OWNED_DIRS=/app/node_modules
  selenium:
    extends:
      file: docker-services.yml
      service: selenium
volumes:
  node_modules:
  home:
