version: '2.1'
services:
  app:
    image: node:7.7.4
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    working_dir: /app
    links:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
      - SELENIUM_BROWSER=chrome
  selenium:
    image: selenium/standalone-chrome:3.2.0
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
volumes:
  node_modules:
