// flow-typed signature: e6adeffb1e727d26d987cd121b6fbad4
// flow-typed version: <<STUB>>/axe-webdriverjs_v^0.5.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axe-webdriverjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'axe-webdriverjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axe-webdriverjs/lib/index' {
  declare module.exports: any;
}

declare module 'axe-webdriverjs/lib/inject' {
  declare module.exports: any;
}

declare module 'axe-webdriverjs/lib/normalize-context' {
  declare module.exports: any;
}

declare module 'axe-webdriverjs/lib/warn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axe-webdriverjs/lib/index.js' {
  declare module.exports: $Exports<'axe-webdriverjs/lib/index'>;
}
declare module 'axe-webdriverjs/lib/inject.js' {
  declare module.exports: $Exports<'axe-webdriverjs/lib/inject'>;
}
declare module 'axe-webdriverjs/lib/normalize-context.js' {
  declare module.exports: $Exports<'axe-webdriverjs/lib/normalize-context'>;
}
declare module 'axe-webdriverjs/lib/warn.js' {
  declare module.exports: $Exports<'axe-webdriverjs/lib/warn'>;
}
