// flow-typed signature: 0878a42e61d71e170aacd4691aa73ec3
// flow-typed version: <<STUB>>/axe-core_v^2.1.7/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axe-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'axe-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axe-core/axe' {
  declare module.exports: any;
}

declare module 'axe-core/axe.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axe-core/axe.js' {
  declare module.exports: $Exports<'axe-core/axe'>;
}
declare module 'axe-core/axe.min.js' {
  declare module.exports: $Exports<'axe-core/axe.min'>;
}
