// flow-typed signature: 015861863f039d3329be44aa550da4ac
// flow-typed version: <<STUB>>/csv-stringify_v^1.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-stringify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-stringify/lib/index' {
  declare module.exports: any;
}

declare module 'csv-stringify/lib/sync' {
  declare module.exports: any;
}

declare module 'csv-stringify/samples/api.callback' {
  declare module.exports: any;
}

declare module 'csv-stringify/samples/api.pipe' {
  declare module.exports: any;
}

declare module 'csv-stringify/samples/api.stream' {
  declare module.exports: any;
}

declare module 'csv-stringify/samples/options.header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv-stringify/lib/index.js' {
  declare module.exports: $Exports<'csv-stringify/lib/index'>;
}
declare module 'csv-stringify/lib/sync.js' {
  declare module.exports: $Exports<'csv-stringify/lib/sync'>;
}
declare module 'csv-stringify/samples/api.callback.js' {
  declare module.exports: $Exports<'csv-stringify/samples/api.callback'>;
}
declare module 'csv-stringify/samples/api.pipe.js' {
  declare module.exports: $Exports<'csv-stringify/samples/api.pipe'>;
}
declare module 'csv-stringify/samples/api.stream.js' {
  declare module.exports: $Exports<'csv-stringify/samples/api.stream'>;
}
declare module 'csv-stringify/samples/options.header.js' {
  declare module.exports: $Exports<'csv-stringify/samples/options.header'>;
}
